export enum ModalKey {
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CROP_IMAGE = 'CROP_IMAGE',
  GENERAL = 'GENERAL',
  STATISTICS_VIEW_OPTIONS = 'STATISTICS_VIEW_OPTIONS',
  ADS_REQUEST_VIEW_OPTIONS = 'ADS_REQUEST_VIEW_OPTIONS',
  CANCEL_REQUEST = 'CANCEL_REQUEST',
  PANEL_DETAIL = 'PANEL_DETAIL',
  COORDINATE_PICKING = 'COORDINATE_PICKING',
  LOCATION_PICKING = 'LOCATION_PICKING',
  LOCATION_VIEW_OPTIONS = 'LOCATION_VIEW_OPTIONS',
  PANEL_VIEW_OPTIONS = 'PANEL_VIEW_OPTIONS',
}
