export enum ModalKey {
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CROP_IMAGE = 'CROP_IMAGE',
  GENERAL = 'GENERAL',
  CANCEL_REQUEST = 'CANCEL_REQUEST',
  PANEL_DETAIL = 'PANEL_DETAIL',
  REPORT_DETAIL = 'REPORT_DETAIL',
}
