export enum ModalKey {
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CERATE_ITEM = 'CREATE_ITEM',
  CROP_IMAGE = 'CROP_IMAGE',
  GENERAL = 'GENERAL',
  STATISTICS_VIEW_OPTIONS = 'STATISTICS_VIEW_OPTIONS',
}
