name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        if: "contains(github.event.head_commit.message, '[ci build]')"
        run: curl -v -L "https://api.render.com/deploy/srv-clq5l6hjvg7s73e3bp1g?key=fc2PDN9b780"
