name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        if: "contains(github.event.head_commit.message, '[ci build]')"
        run: curl -v -L "https://api.render.com/deploy/srv-clq5l6hjvg7s73e3bp1g?key=fc2PDN9b780"
